services:
  analysis-env:
    #image: rocker/rstudio:4.4.2 
    image: mycontainer
    ports:
      - "8787:8787"
    volumes:    # to mount local to remote container
      - .:/home/rstudio/work
    environment:     # environment variables
      PASSWORD: "password"
      DISABLE_AUTH: true # disable login screen and need for password


# have a second container -> can open both at the same time on different tabs

  analysis-env2:
    image: rocker/rstudio:4.4.2 
    ports:
      - "7777:8787" # different port number for different container
    volumes:    # to mount local to remote container
      - .:/home/rstudio/work2 
    environment:     # environment variables
      PASSWORD: "password"
      DISABLE_AUTH: true # disable login screen and need for password


